version: "3.3"

volumes:
  db-data:
  core:
  vendor:


networks:
  proxy:
    external: true
  internal:
    external: false

services:
  drupal:
    build:
      context: ./docker/drupal-php
      args:
        DRUPAL_VERSION: ${DRUPAL_VERSION}
    volumes:
      - core:/var/www/html/core
      - vendor:/var/www/html/vendor
      - ./modules:/var/www/html/modules
      - ./profiles:/var/www/html/profiles
      - ./themes:/var/www/html/themes
      - ./sites:/var/www/html/sites
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
    depends_on:
      - database
    labels:
      - traefik.enable=false
    networks:
      - internal

  server:
    build: 
      context: ./docker/apache
      args:
        APACHE_VERSION: ${SERVER_VERSION}
    volumes:
      - core:/usr/local/apache2/htdocs/core
      - vendor:/usr/local/apache2/htdocs/vendor
      - ./sites:/usr/local/apache2/htdocs/sites
      - ./themes:/usr/local/apache2/htdocs/themes
      - ./modules:/var/www/html/modules
      - ./.htaccess:/usr/local/apache2/htdocs/.htaccess
    depends_on:
      - drupal
    labels:
      - traefik.http.routers.server-${COMPOSE_PROJECT_NAME}.rule=Host(`www.${COMPOSE_PROJECT_NAME}.localhost`)
      - traefik.docker.network=proxy
      - traefik.http.services.server-${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80
    networks:
      - internal
      - proxy

  database:
    image: mysql:${DATABASE_VERSION}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
     - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    labels:
      - traefik.enable=false
    networks:
      - internal
