version: '3'

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  drupal:
    build:
      context: ./docker/drupal-php
      args:
        DRUPAL_VERSION: ${DRUPAL_VERSION}
    container_name: drupal_${PROJECT_NAME}
    volumes:
      - app:/var/www/html
      - ./modules:/var/www/html/modules
      - ./profiles:/var/www/html/profiles
      - ./themes:/var/www/html/themes
      - ./sites:/var/www/html/sites
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
    depends_on:
      - database
    labels:
      - traefik.enable=false
    networks:
      - internal

  server:
    build: 
      context: ./docker/nginx
      args:
        NGINX_VERSION: ${SERVER_VERSION}
    container_name: server_${PROJECT_NAME}
    volumes:
      - app:/var/www/html
    depends_on:
      - drupal
    labels:
      - traefik.backend=server_${PROJECT_NAME}
      - traefik.frontend.rule=Host:www.${PROJECT_NAME}.loc
      - traefik.docker.network=proxy
      - traefik.port=80
    networks:
      - internal
      - proxy

  database:
    image: mysql:${DATABASE_VERSION}
    container_name: database_${PROJECT_NAME}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
     - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    labels:
      - traefik.enable=false
    networks:
      - internal

volumes:
  app:
  db-data: